In [1]:
import torch
from torch.distributions import Poisson

In [10]:
D = 1
S = 3
B = 4

h = 0.01
device = torch.device("cpu")
rates = torch.rand((B,D,S))

x = torch.randint(0,S,(B,D))

In [11]:
x

tensor([[0],
        [2],
        [1],
        [0]])

In [14]:
diffs = torch.arange(S, device=device).view(1,1,S) - x.view(B,D,1)
poisson_dist = torch.distributions.poisson.Poisson(rates*h)
jump_nums = poisson_dist.sample().to(device)
adj_diffs = jump_nums * diffs
overall_jump = torch.sum(adj_diffs, dim=2)
xp = x + overall_jump
x_new = torch.clamp(xp, min=0, max=S-1)

In [16]:
x_new

torch.Size([4, 1])

In [17]:
x

tensor([[0],
        [2],
        [1],
        [0]])

In [20]:
diffs

tensor([[[ 0,  1,  2]],

        [[-2, -1,  0]],

        [[-1,  0,  1]],

        [[ 0,  1,  2]]])