In [2]:
import os
import sys
import torch
from conditional_rate_matching.configs.experiments_configs.crm.crm_experiments_graph import experiment_comunity_small
from conditional_rate_matching.models.generative_models.crm import CRM

from pprint import pprint
from dataclasses import asdict
import torch.nn.functional as F

In [3]:
graph_config = experiment_comunity_small()
#pprint(asdict(graph_config))
crm:CRM = CRM(config=graph_config)

In [18]:
databatch0 = next(crm.dataloader_0.train().__iter__())
databatch1 = next(crm.dataloader_1.train().__iter__())
x0 = databatch0[0]
x1 = databatch1[0]
time1 = torch.ones(x0.shape[0])

posterior_estimate = F.softmax(crm.forward_rate.classify(x1,time1),dim=1)

x0_ = x0.unsqueeze(-1).repeat((1,1,x0.shape[0])).permute(2,1,0).long()
posterior_estimate_ = posterior_estimate.unsqueeze(-1).repeat((1,1,1,x0.shape[0]))
cost = torch.gather(posterior_estimate_,2,x0_.unsqueeze(2)).squeeze()

In [5]:
posterior_estimate_1d = posterior_estimate[:,0,:]
x0_1d = x0[:,0]
x1_1d = x1[:,0]

x0_1d_ = x0_1d.unsqueeze(-1).repeat((1,x0_1d.shape[0])).permute(1,0).long()
posterior_estimate_1d = posterior_estimate_1d.unsqueeze(-1).repeat((1,1,x0_1d.shape[0]))
cost_1d = torch.gather(posterior_estimate_1d,1,x0_1d_.unsqueeze(1)).squeeze()
cost_1d.shape

torch.Size([20, 20])

In [14]:
x0[:,9]

tensor([0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0.,
        1., 0.])

In [17]:
cost[0,9,3]

tensor(0.0119, grad_fn=<SelectBackward0>)

In [11]:
posterior_estimate[:,9,:]

tensor([[0.0119, 0.0066],
        [0.0081, 0.0088],
        [0.0069, 0.0057],
        [0.0119, 0.0066],
        [0.0083, 0.0091],
        [0.0079, 0.0112],
        [0.0070, 0.0038],
        [0.0119, 0.0066],
        [0.0074, 0.0063],
        [0.0116, 0.0075],
        [0.0074, 0.0063],
        [0.0074, 0.0063],
        [0.0125, 0.0075],
        [0.0079, 0.0102],
        [0.0080, 0.0041],
        [0.0078, 0.0036],
        [0.0084, 0.0117],
        [0.0119, 0.0066],
        [0.0120, 0.0085],
        [0.0081, 0.0088]], grad_fn=<SliceBackward0>)

In [ ]:
posterior_estimate[]

In [167]:
x0_.unsqueeze(2).shape

torch.Size([20, 190, 1, 20])

In [141]:
x0_1d_[0]

tensor([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [146]:
cost[0,4]

tensor(0.0038, grad_fn=<SelectBackward0>)

In [147]:
# posterior_estimate_1d[:,:,0]

In [88]:
cost = torch.gather(posterior_equal_probability,2,x0_)


In [91]:
posterior_equal_probability[3,0]

tensor([0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024,
        0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024,
        0.0024, 0.0024], grad_fn=<SelectBackward0>)

In [87]:
cost = cost.sum(axis=1).min()

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)