In [3]:
import torch

import torch

def compute_first_moment(S, i, j, w_10, w_1t, w_t0):
    # Kronecker delta in PyTorch
    kronecker_delta_ij = (i == j).float()

    # Precompute common terms to simplify the expression
    term_S1 = S + 1  # Term involving S
    part1 = w_10 * (S * kronecker_delta_ij - 1) + 1
    part2 = S * w_10 * kronecker_delta_ij - w_10 + 1

    # Calculate each term of the first moment expression
    term1 = part1 * (S + w_1t * w_t0 * term_S1 - w_1t * term_S1 - w_t0 * term_S1 + 1) / 2
    term2 = part2 * (S * i * w_1t * w_t0 * kronecker_delta_ij - i * w_1t * w_t0 + i * w_1t - j * w_1t * w_t0 + j * w_t0)

    # Combine terms to compute the first moment
    first_moment = (term1 + term2) / (part1 * part2)

    return first_moment


def compute_second_moment_complex(S, i, j, w_10, w_1t, w_t0):
    # Kronecker delta in PyTorch
    kronecker_delta_ij = (i == j).float()

    # Precompute common terms to simplify the expression
    term_S0 = 2 * S**2 + 3 * S + 1  # Term involving S
    part1 = w_10 * (S * kronecker_delta_ij - 1) + 1
    part2 = S * w_10 * kronecker_delta_ij - w_10 + 1

    # Calculate each term of the second moment expression
    term1 = part1 * (term_S0 + w_1t * w_t0 * term_S0 - w_1t * term_S0 - w_t0 * term_S0 + 1) / 6
    term2 = part2 * (S * i**2 * w_1t * w_t0 * kronecker_delta_ij - i**2 * w_1t * w_t0 + i**2 * w_1t - j**2 * w_1t * w_t0 + j**2 * w_t0)

    # Combine terms to compute the second moment
    second_moment = (term1 + term2) / (part1 * part2)

    return second_moment


In [12]:

# Example usage
S_value = torch.tensor(10.0)  # State space size
i = torch.randint(0,10,(3,4)).float()  # Tensor for i
j = torch.randint(0,10,(3,4)).float()  # Tensor for j, must be the same size as i
w_10_value = torch.tensor(0.1)  # Weight w_10
w_1t_value = torch.tensor(0.2)  # Weight w_1t
w_t0_value = torch.tensor(0.3)  # Weight w_t0

# Call the function
first_moment = compute_first_moment(S_value, i, j, w_10_value, w_1t_value, w_t0_value)
print(first_moment)
# Call the function
second_moment_complex = compute_second_moment_complex(S_value, i, j, w_10_value, w_1t_value, w_t0_value)
print(second_moment_complex)

variance = second_moment_complex - first_moment**2
variance

tensor([[5.0889, 6.4444, 4.0000, 5.2667],
        [3.6842, 4.5111, 6.1778, 4.9556],
        [4.3556, 6.6000, 6.1333, 5.0667]])
tensor([[37.0074, 48.2296, 25.0296, 32.2963],
        [19.6877, 31.7630, 43.6963, 29.8074],
        [29.7407, 49.6296, 46.3630, 31.4296]])


tensor([[11.1106,  6.6988,  9.0296,  4.5585],
        [ 6.1143, 11.4128,  5.5314,  5.2499],
        [10.7699,  6.0696,  8.7452,  5.7585]])

In [14]:
torch.randn(10)

tensor([-1.1277, -1.4929,  1.0785,  0.2809,  0.9458,  0.3655, -0.3089,  1.3626,
        -1.1439, -1.0441])